function fun_validaCampos(){var a=!1;for(i=0;i<arguments.length;i++)arguments[i].css({border:"1px solid #ccc"});for(i=0;i<arguments.length;i++)0==arguments[i].val().trim().length&&(a=!0,arguments[i].css({border:"1px solid red"}));return a}function fun_removeEspacos(a){return a.replace(/^\s*/,"").replace(/\s*$/,"")}function fun_validaURL(a){return/^(http(s)?:\/\/)?(((www)\.){1}|(\w+(\.|\-){1})){1}((\w)|(\.))+((\w)*|([_%:~?=!+\#(),&.\-\/]))+$/.test(a)}
function fun_isNumeric(a){return/^[-]?\d*\.?\d*$/.test(a)}function fun_validaEmail(a){return/^[\w!#$%&'*+\/=?^`{|}~-]+(\.[\w!#$%&'*+\/=?^`{|}~-]+)*@(([\w-]+\.)+[A-Za-z]{2,6}|\[\d{1,3}(\.\d{1,3}){3}\])$/.test(a)}
function fun_validaData(a){if(/^((0[1-9]|[12]\d)\/(0[1-9]|1[0-2])|30\/(0[13-9]|1[0-2])|31\/(0[13578]|1[02]))\/(19|20)?\d{2}$/.test(a)){var b=!0,c=a.substring(0,2),d=a.substring(3,5);a=a.substring(6,10);(4==d||6==d||9==d||11==d)&&30<c?b=!1:0!=a%4&&2==d&&28<c?b=!1:0==a%4&&2==d&&29<c&&(b=!1);return b}return!1}function fun_setCookie(a,b,c){var d=new Date;d.setDate(d.getDate()+c);b=escape(b)+(null==c?"":"; expires="+d.toUTCString());document.cookie=a+"="+b}
function fun_getCookie(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].substr(0,e[b].indexOf("=")),d=e[b].substr(e[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a)return unescape(d);return null}
function get_date(a,b){var c,d,e=/\\?([a-z])/gi,f,g=function(a,b){return(a+="").length<b?Array(++b-a.length).join("0")+a:a};f=function(a,b){return d[a]?d[a]():b};d={d:function(){return g(d.j(),2)},w:function(){return c.getDay()},j:function(){return c.getDate()},m:function(){return g(d.n(),2)},n:function(){return c.getMonth()+1},Y:function(){return c.getFullYear()},y:function(){return(d.Y()+"").slice(-2)}};this.date=function(a){c=b?"string"==typeof b?new Date(b.replace(/-/g,"/")):new Date(b):new Date;
return a.replace(e,f)};return this.date(a)}function add_date(a,b,c){a&&10==a.trim().length&&(a+=" 01:00:00");var d=new Date(a.replace(/-/g,"/"));c=c?c:"MONTH";switch(c){case "DAY":d.setDate(d.getDate()+b);break;case "MONTH":d.setMonth(d.getMonth()+b);break;case "YEAR":d.setFullYear(d.getFullYear()+b);break;case "WEEK":d.setDate(d.getDate()+7*b)}b=get_date("Y-m-d",d.getTime());("MONTH"==c||"YEAR"==c)&&10<=a.length&&a.substr(8,2)!=b.substr(8,2)&&(b=sub_date(b.substr(0,7)+"-01",1,"DAY"));return b}
function sub_date(a,b,c){return add_date(a,-b,c)}function diff_date(a,b,c,d){var e=0;c=c?c:"MONTH";if(d=d?d:1)if(0<datecmp(a,b))for(;0<datecmp(a,b);)a=sub_date(a,d,c),e++;else if(0>datecmp(a,b))for(;0>datecmp(a,b);)a=add_date(a,d,c),e--;return e}function datecmp(a,b){a=new Date(a.replace(/-/g,"/"));b=new Date(b.replace(/-/g,"/"));var c=a.getTime()-b.getTime();return 0>c?-1:0<c?1:0}function datebtw(a,b,c){var d,e;return 0>(d=datecmp(a,b))?d:0<(e=datecmp(a,c))?e:0}
function getData(a){var b=new Date,c=[];c[0]=b.getDate().toString();c[0]=1==c[0].length?"0"+c[0]:c[0];c[1]=(b.getMonth()+1).toString();c[1]=1==c[1].length?"0"+c[1]:c[1];c[2]=b.getFullYear();return c.join(a)}function date_reverse(a,b){a=a.split(b);var c=[];c[0]=a[2];c[1]=a[1];c[2]=a[0];return c}
function fun_validaHora(a){if(5==a.trim().length){if(0>parseInt(a.substring(0,2),10)||23<parseInt(a.substring(0,2),10)||0>parseInt(a.substring(3,6),10)||59<parseInt(a.substring(3,6),10))return!1}else return!1;return!0}function get_nome_meses(a){var b="Janeiro Fevereiro Mar\u00e7o Abril Maio Junho Julho Agosto Setembro Outubro Novembro Dezembro".split(" ");a=parseFloat(a);return 0>=a||12<a?b:b[a-1]}
function get_array_anos(a,b){var c=[],d=parseFloat(get_date("Y"));b=void 0!==b?b:!0;for(var e=0;e<a;e++){var f=d+e;b&&(f-=Math.ceil(a/2-0.5));c.push(f)}return c}function json(a){return JSON.stringify(a)}function validaData(a){return a&&fun_validaData(a.format_date_br())};
